# Vectorisation Demo


In [60]:
import numpy as np

a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [61]:
import time

b = np.random.rand(3)
print(b.shape)
c = np.random.rand(3)
print(c.shape)

tic = time.time()
d = np.dot(b,c) # two 1D array multiplication
toc = time.time()# second since 1970-01-01
print('Vectorised version: ' + str(1000*(toc-tic)) + ' ms')
print(d)

(3,)
(3,)
Vectorised version: 1.1920928955078125 ms
0.535877198375921


In [81]:
d = 0
tic = time.time()
for i in range(3):
    d += b[i]*c[i] # you multiply b and c of the first row and get d
    #you then multiply b and c of the second row and add that number to the previous d and so on
    #note, b[i] means the row number that matches the i in for loop
    print('b', b[i], 'c', c[i],'d', d)
toc = time.time()


print('hu', d)
print("For loop:" + str(1000*(toc-tic)) + 'ms')

b 0.05540657299331653 c 0.19886820677963224 d 0.011018605814985658
b 0.8738834542366543 c 0.1391085500536654 d 0.1325832660497353
b 0.7337243745394482 c 0.549653175389368 d 0.535877198375921
hu 0.535877198375921
For loop:1.8701553344726562ms


In [72]:
# As above, for loop is slower than vectorisation!!! 

In [71]:
d = 0
tic = time.time()
for i in range(3):
    d += b*c # you multiply b and c of the first row and get d,
    #you then multiply b and c of the second row and add that number to the previous d and so on
    print('b', b, 'c', c,'d', d)
toc = time.time()


print('hu', d)
print("For loop:" + str(1000*(toc-tic)) + 'ms')

b [0.05540657 0.87388345 0.73372437] c [0.19886821 0.13910855 0.54965318] d [0.01101861 0.12156466 0.40329393]
b [0.05540657 0.87388345 0.73372437] c [0.19886821 0.13910855 0.54965318] d [0.02203721 0.24312932 0.80658786]
b [0.05540657 0.87388345 0.73372437] c [0.19886821 0.13910855 0.54965318] d [0.03305582 0.36469398 1.2098818 ]
hu [0.03305582 0.36469398 1.2098818 ]
For loop:2.173900604248047ms


# Broadcasting Example

In [5]:
import numpy as np

A = np.array([[56.0,0.0,4.4,68.0],
            [1.2,104.0,52.0,8.0],
              [1.8,135.0,99.0,0.9]])

print(A)
A.shape

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


(3, 4)

In [7]:
cal = A.sum(axis = 0) #axis = 0 equal sum of the each column of variable A
print(cal)
cal.shape

[ 59.  239.  155.4  76.9]


(4,)

In [9]:
# the below allows each 'A' element to be divided by the corrsponding column sum 
# despite cal and A is in different np.array size.
# This is a method of broadcasting in numpy

percentage = 100*(A/cal)

print(percentage)


[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]
